import Head from "next/head";
import Image, { StaticImageData } from "next/image";
import { Button } from "../components/Button";
import einzeltanz from "../public/einzeltanz.png";
import formation from "../public/formation.png";
import kindertanzen from "../public/kindertanzen.png";
import heroBanner from "../public/heroBanner.png";
import vereinsBild from "../public/vereinsbild.png";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <HeroSection />
        <CourseSection />
        <AssociationSection />
        <Stats />
        {/*  <div className="flex bg-accent">*/}
        {/*    <div className="flex">*/}
        {/*      <Image src={mitglieder} alt="" />*/}
        {/*      <div className="flex flex-col text-black">*/}
        {/*        <div className="h1 text-black"> {">"} 600</div>*/}
        {/*        <div className="h6 uppercase text-black">Mitglieder</div>*/}
        {/*      </div>*/}
        {/*    </div>*/}
        {/*    <div className="flex">*/}
        {/*      <Image src={teams} alt="" />*/}
        {/*      <div className="flex flex-col text-black">*/}
        {/*        <div className="h1 text-black">8</div>*/}
        {/*        <div className="h6 uppercase text-black">Formationsteams</div>*/}
        {/*      </div>*/}
        {/*    </div>*/}
        {/*    <div className="flex">*/}
        {/*      <Image src={bayernpokalsiege} alt="" />*/}
        {/*      <div className="flex flex-col text-black">*/}
        {/*        <div className="h1 text-black">25x</div>*/}
        {/*        <div className="h6 uppercase text-black">Bayernpokalsieger</div>*/}
        {/*      </div>*/}
        {/*    </div>*/}
        {/*  </div>*/}
        {/*  <div className="flex flex-col items-center bg-white">*/}
        {/*    <h1 className="h1 text-dark-grey">News</h1>*/}
        {/*    <div>Posts</div>*/}
        {/*    <CTA text="Mehr erfahren" />*/}
        {/*  </div>*/}
        {/*</div>*/}
      </main>
    </>
  );
}

const HeroSection = () => (
  <div className="relative bg-primary">
    <section className="relative z-10 mx-auto flex max-w-screen-md flex-col items-center space-y-6 py-32 px-10">
      <h1 className="h4 text-center uppercase text-accent">
        Herzlich Willkommen im RGC
      </h1>
      <h2 className="h6 text-center uppercase">
        Ihrem Verein für Tanzsport in Nürberg / Fürth
      </h2>
      <p className="body-font text-center">
        Erleben Sie die faszinierende Welt des Tanzens! Bei uns finden Sie
        alles, was das Tänzerherz begehrt - von Latein, Standard und
        Formationstanzen bis hin zu Breitensport, Kindertanzen und Breakdance.
        Werden Sie Teil unserer Tanzfamilie und erleben Sie mit uns
        unvergessliche Momente auf der Tanzfläche.
      </p>
      <Button>Komm vorbei</Button>
    </section>
    <div className="absolute inset-0 h-full">
      <Image src={heroBanner} alt="" className="object-cover" fill />
    </div>
  </div>
);

const CourseSection = () => {
  return (
    <div className="space-y-10 bg-secondary p-24">
      <div className="flex flex-col items-center gap-10">
        <h1 className="h1 text-white">Unser Angebot</h1>
        <p className="body-font px-80 text-center text-primary">
          Bei uns finden Sie alles, was das Tänzerherz begehrt - von Latein,
          Standard und Formationstanzen bis hin zu Breitensport, Kindertanzen
          und Breakdance.
        </p>
      </div>
      <div className="mx-auto grid max-w-screen-lg grid-cols-3 gap-6 text-white">
        <CourseCard
          title="Einzeltanz"
          description="Egal ob Standard, Latein oder Kombi - unsere erfahrenen Trainer bringen Sie auf das nächste Level und unterstützen Sie bei der Teilnahme an Wettkämpfen."
          image={einzeltanz}
        />
        <CourseCard
          title="Formation"
          description="Unsere acht Formationsteams begeistern mit präzisen Choreografien und beeindruckender Teamarbeit. Wir finden für jeden das passende Team!"
          image={formation}
        />
        <CourseCard
          title="Kindertanzen"
          description="Fördern Sie die kreative Entwicklung Ihres Kindes! Unsere erfahrenen Tanzlehrer bringen den Kindern spielerisch Rhythmusgefühl und koordinative Fähigkeiten bei."
          image={kindertanzen}
        />
      </div>
    </div>
  );
};

interface CourseCardProps {
  title: string;
  description: string;
  image: StaticImageData;
}

const CourseCard = ({ title, description, image }: CourseCardProps) => {
  return (
    <div className="flex flex-col rounded-lg bg-primary">
      <div className="h-60">
        <Image
          src={image}
          alt=""
          className="h-full rounded-t-lg object-cover"
        />
      </div>
      <div className="flex grow flex-col gap-6 p-8">
        <div className="h4 uppercase">{title}</div>
        <div className="body-font grow">{description}</div>
        <Button>Mehr erfahren</Button>
      </div>
    </div>
  );
};

const AssociationSection = () => {
  return (
    <div className="grid grid-cols-2 text-white">
      <div>
        <Image src={vereinsBild} alt="" className="h-full object-cover" />
      </div>
      <div className="flex basis-1/2 flex-col justify-center gap-8 bg-primary px-28">
        <p className="h5 uppercase text-mid-grey">
          Mit Herz und Rhythmus - unser Verein und seine Trainer
        </p>
        <h1 className="h1">Über uns</h1>
        <p className="body-font text-mid-grey">
          Wir sind der RGC Nürnberg - ein Verein, der die Leidenschaft für den
          Tanzsport in all seinen Facetten vereint. Seit unserer Gründung im
          Jahr 1963 steht die Freude am Tanzen und die Förderung der Tanzkultur
          im Mittelpunkt unserer Arbeit. Erfahren Sie mehr über unsere
          Geschichte und unsere Ziele auf dieser Seite.
        </p>
        <Button>Mehr erfahren </Button>
      </div>
    </div>
  );
};

const Stats = () => {
  return (
    <div className="flex justify-center bg-accent">
      <div className="stats max-w-screen-lg space-x-10 bg-accent py-32">
        <div className="stat">
          <div className="stat-figure">
            <MemberIcon />
          </div>
          <div className="h1 stat-value text-black"> {">"} 600</div>
          <div className="h6 stat-desc uppercase text-black">Mitglieder</div>
        </div>
        <div className="stat">
          <div className="stat-figure">
            <TeamsIcon />
          </div>
          <div className="h1 stat-value text-black">8</div>
          <div className="h6 stat-desc uppercase text-black">
            Formationsteams
          </div>
        </div>
        <div className="stat">
          <div className="stat-figure">
            <TrophyIcon />
          </div>
          <div className="h1 stat-value text-black">25x</div>
          <div className="h6 stat-desc uppercase text-black">
            Bayernpokalsieger
          </div>
        </div>
      </div>
    </div>
  );
};

const MemberIcon = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    height="48"
    viewBox="0 96 960 960"
    width="48"
  >
    <path d="M0 816v-53q0-38.567 41.5-62.784Q83 676 150.376 676q12.165 0 23.395.5Q185 677 196 678.652q-8 17.348-12 35.165T180 751v65H0Zm240 0v-65q0-32 17.5-58.5T307 646q32-20 76.5-30t96.5-10q53 0 97.5 10t76.5 30q32 20 49 46.5t17 58.5v65H240Zm540 0v-65q0-19.861-3.5-37.431Q773 696 765 678.727q11-1.727 22.171-2.227 11.172-.5 22.829-.5 67.5 0 108.75 23.768T960 763v53H780Zm-480-60h360v-6q0-37-50.5-60.5T480 666q-79 0-129.5 23.5T300 751v5ZM149.567 646Q121 646 100.5 625.438 80 604.875 80 576q0-29 20.562-49.5Q121.125 506 150 506q29 0 49.5 20.5t20.5 49.933Q220 605 199.5 625.5T149.567 646Zm660 0Q781 646 760.5 625.438 740 604.875 740 576q0-29 20.562-49.5Q781.125 506 810 506q29 0 49.5 20.5t20.5 49.933Q880 605 859.5 625.5T809.567 646ZM480 576q-50 0-85-35t-35-85q0-51 35-85.5t85-34.5q51 0 85.5 34.5T600 456q0 50-34.5 85T480 576Zm.351-60Q506 516 523 498.649t17-43Q540 430 522.851 413t-42.5-17Q455 396 437.5 413.149t-17.5 42.5Q420 481 437.351 498.5t43 17.5ZM480 756Zm0-300Z" />
  </svg>
);

const TeamsIcon = () => (
  <svg
    width="150"
    height="150"
    viewBox="0 0 150 150"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M150 116.24C150 112.654 147.7 109.631 144.48 108.555C144.94 107.531 145.247 106.352 145.247 105.123C145.247 100.717 141.721 97.1311 137.376 97.0287V86.9877C137.376 83.8115 137.99 80.7377 139.216 77.7664L144.378 65.3689C145.86 61.834 146.627 58.043 146.627 54.2008V17.6742C146.627 13.2172 142.998 9.52869 138.501 9.52869C137.274 9.52869 136.099 9.78484 135.077 10.2971C134.003 7.06967 130.937 4.76434 127.411 4.76434C126.184 4.76434 125.008 5.02049 123.986 5.53279C122.913 2.30533 119.847 0 116.32 0C112.794 0 109.727 2.30533 108.654 5.53279C107.632 5.02049 106.457 4.76434 105.23 4.76434C100.835 4.76434 97.2572 8.29918 97.155 12.6537H86.7802C83.6116 12.6537 80.5451 12.0389 77.5809 10.8094L65.2129 5.63525C61.6865 4.14959 57.9046 3.38115 54.0715 3.38115H17.632C13.1857 3.38115 9.50597 7.01844 9.50597 11.5266C9.50597 12.7561 9.76149 13.9344 10.2726 14.959C7.0528 16.0348 4.75298 19.1086 4.75298 22.6434C4.75298 23.873 5.00851 25.0512 5.51958 26.0758C2.29982 27.1516 0 30.2254 0 33.7602C0 37.2951 2.29982 40.3689 5.51958 41.4447C5.00851 42.4693 4.75298 43.6475 4.75298 44.877C4.75298 49.1291 8.07494 52.6127 12.2657 52.9201L12.6746 63.0123C12.6746 66.1885 12.0613 69.2623 10.8347 72.2336L5.67292 84.6311C4.1908 88.166 3.42418 91.957 3.42418 95.7992V132.326C3.42418 136.783 7.0528 140.471 11.5502 140.471C12.7768 140.471 13.9523 140.215 14.9744 139.703C16.0477 142.93 19.1141 145.236 22.6405 145.236C23.8671 145.236 25.0426 144.98 26.0647 144.467C27.138 147.695 30.2044 150 33.7308 150C37.2572 150 40.3237 147.695 41.3969 144.467C42.4191 144.928 43.5945 145.236 44.8211 145.236C49.2164 145.236 52.7939 141.701 52.8961 137.346H63.2709C66.4395 137.346 69.506 137.961 72.4702 139.191L84.8381 144.365C88.4157 145.85 92.1465 146.619 95.9795 146.619H132.419C136.865 146.619 140.545 142.982 140.545 138.473C140.545 137.244 140.29 136.066 139.779 135.041C142.998 133.965 145.298 130.891 145.298 127.357C145.298 126.127 145.043 124.949 144.531 123.924C147.649 122.848 150 119.826 150 116.24ZM102.215 12.9098C102.215 11.2705 103.543 9.88729 105.23 9.88729C106.865 9.88729 108.245 11.2193 108.245 12.9098V46.3115C108.245 47.7459 109.37 48.8729 110.801 48.8729C112.232 48.8729 113.356 47.7459 113.356 46.3115V8.14549C113.356 6.50615 114.685 5.12295 116.371 5.12295C118.058 5.12295 119.387 6.45492 119.387 8.14549V42.418C119.387 43.8525 120.511 44.9795 121.942 44.9795C123.373 44.9795 124.497 43.8525 124.497 42.418V12.9098C124.497 11.2705 125.826 9.88729 127.513 9.88729C129.148 9.88729 130.528 11.2193 130.528 12.9098V47.1824C130.528 48.6168 131.652 49.7439 133.083 49.7439C134.514 49.7439 135.639 48.6168 135.639 47.1824V17.6742C135.639 16.0348 136.968 14.6516 138.654 14.6516C140.341 14.6516 141.669 15.9836 141.669 17.6742V54.2008C141.669 57.377 141.056 60.502 139.83 63.4221L134.668 75.8197C133.186 79.3545 132.419 83.1455 132.419 86.9877V97.0287H102.368V87.6537C102.368 80.584 99.8126 73.7705 95.1107 68.4426C92.9131 65.9324 91.2777 63.0635 90.2555 59.8873L88.109 53.0738H99.8126C101.244 53.0738 102.368 51.9467 102.368 50.5123C102.368 50.4098 102.317 50.3586 102.317 50.2561C102.317 50.1537 102.368 50.1025 102.368 50V12.9098H102.215ZM67.2572 96.5164L64.753 88.6271C63.5264 84.7848 61.5332 81.25 58.8756 78.2275C56.1669 75.1537 54.3782 71.4139 53.5094 67.418L61.2266 64.959C65.1107 63.7295 68.586 61.7316 71.6013 59.0676C74.77 56.25 78.6031 54.4057 82.6917 53.5861L85.1959 61.4754C86.4225 65.3688 88.4157 68.8525 91.0732 71.875C93.7819 74.9488 95.6218 78.6885 96.4395 82.6844L88.6712 85.1434C84.787 86.3729 81.3117 88.3709 78.2964 91.0348C75.1789 93.8012 71.3458 95.6967 67.2572 96.5164ZM9.86371 44.9283C9.86371 43.2889 11.1925 41.9057 12.879 41.9057H46.201C47.632 41.9057 48.7564 40.7787 48.7564 39.3443C48.7564 37.9098 47.632 36.7828 46.201 36.7828H8.07495C6.43951 36.7828 5.05961 35.4508 5.05961 33.7602C5.05961 32.0697 6.3884 30.7377 8.07495 30.7377H42.2658C43.6968 30.7377 44.8211 29.6107 44.8211 28.1762C44.8211 26.7418 43.6968 25.6148 42.2658 25.6148H12.8279C11.1925 25.6148 9.8126 24.2828 9.8126 22.5922C9.8126 20.9529 11.1414 19.5697 12.8279 19.5697H47.0187C48.4497 19.5697 49.5741 18.4426 49.5741 17.0082C49.5741 15.5738 48.4497 14.4467 47.0187 14.4467H17.5809C15.9455 14.4467 14.5656 13.1148 14.5656 11.4242C14.5656 9.78484 15.8944 8.40164 17.5809 8.40164H54.0204C57.1891 8.40164 60.2555 9.01639 63.2197 10.2459L75.5877 15.4201C79.1141 16.9057 82.8961 17.6742 86.7291 17.6742H97.1039V47.7971H87.3935C80.3407 47.7971 73.5434 50.3586 68.2283 55.0717C65.724 57.2746 62.862 58.9139 59.6934 59.9385L52.8961 62.0902L52.4361 50.2561C52.4361 50.1025 52.3339 49.9488 52.3339 49.7439C52.2828 49.5902 52.2828 49.4365 52.2317 49.334C51.8739 48.4631 51.0051 47.7971 50.0341 47.8484C49.983 47.8484 49.9318 47.7971 49.8807 47.7971H12.879C11.1925 47.8996 9.86371 46.5676 9.86371 44.9283ZM47.7853 137.141C47.7853 138.781 46.4565 140.164 44.77 140.164C43.1346 140.164 41.7547 138.832 41.7547 137.141V103.689C41.7547 102.254 40.6303 101.127 39.1993 101.127C37.7683 101.127 36.6439 102.254 36.6439 103.689V141.855C36.6439 143.494 35.3152 144.877 33.6286 144.877C31.9932 144.877 30.6133 143.545 30.6133 141.855V107.582C30.6133 106.148 29.4889 105.02 28.0579 105.02C26.6269 105.02 25.5025 106.148 25.5025 107.582V137.09C25.5025 138.73 24.1738 140.113 22.4872 140.113C20.8007 140.113 19.4719 138.781 19.4719 137.09V102.818C19.4719 101.383 18.3475 100.256 16.9165 100.256C15.4855 100.256 14.3612 101.383 14.3612 102.818V132.326C14.3612 133.965 13.0324 135.348 11.3458 135.348C9.7104 135.348 8.3305 134.016 8.3305 132.326V95.7992C8.3305 92.6229 8.94377 89.5492 10.1703 86.5779L15.3322 74.1803C16.8143 70.6455 17.5809 66.8545 17.5809 62.9098L17.2232 52.9713H47.2743L47.632 62.3463C47.632 69.416 50.1874 76.2295 54.8893 81.5574C57.0869 84.0676 58.7223 86.9365 59.7444 90.1127L61.891 96.9262H50.1874C48.7564 96.9262 47.632 98.0533 47.632 99.4877C47.632 99.5902 47.6831 99.6414 47.6831 99.7439C47.6831 99.8463 47.632 99.8975 47.632 100V137.141H47.7853ZM141.874 119.262H107.683C106.252 119.262 105.128 120.389 105.128 121.824C105.128 123.258 106.252 124.385 107.683 124.385H137.121C138.756 124.385 140.136 125.717 140.136 127.408C140.136 129.098 138.807 130.43 137.121 130.43H102.93C101.499 130.43 100.375 131.557 100.375 132.992C100.375 134.426 101.499 135.553 102.93 135.553H132.368C134.003 135.553 135.383 136.885 135.383 138.576C135.383 140.215 134.054 141.598 132.368 141.598H95.9284C92.7598 141.598 89.6934 140.984 86.7291 139.754L74.3611 134.58C70.8347 133.094 67.0528 132.326 63.2197 132.326H52.845V102.203H62.5554C69.6082 102.203 76.4054 99.6414 81.7206 94.9283C84.2249 92.7254 87.0869 91.0861 90.2555 90.0615L97.0528 87.9098V99.6414C97.0528 101.076 98.1771 102.203 99.6082 102.203C99.7104 102.203 99.7615 102.152 99.8637 102.152C99.9659 102.152 100.017 102.203 100.119 102.203H137.121C138.756 102.203 140.136 103.535 140.136 105.225C140.136 106.916 138.807 108.248 137.121 108.248H103.799C102.368 108.248 101.244 109.375 101.244 110.809C101.244 112.244 102.368 113.371 103.799 113.371H141.874C143.509 113.371 144.889 114.703 144.889 116.393C144.889 117.879 143.509 119.262 141.874 119.262Z"
      fill="white"
    />
  </svg>
);

const TrophyIcon = () => (
  <svg
    width="133"
    height="152"
    viewBox="0 0 133 152"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M96.9813 55.8801C118.354 47.8528 133 31.6429 133 12.9472C133 11.4971 131.861 10.3578 130.412 10.3578H111.316C111.472 7.8201 111.575 5.23066 111.575 2.58944C111.575 1.13935 110.437 0 108.988 0H24.0125C22.5634 0 21.4249 1.13935 21.4249 2.58944C21.4249 5.23066 21.5284 7.76831 21.6836 10.3578H2.58755C1.13852 10.3578 0 11.4971 0 12.9472C0 31.6429 14.6455 47.8528 36.0187 55.8801C42.2288 65.0985 50.0432 71.5721 58.7891 74.0061V103.008H34.5697C33.1206 103.008 31.9821 104.147 31.9821 105.597V115.748H23.8054C22.3564 115.748 21.2179 116.887 21.2179 118.337V149.411C21.2179 150.861 22.3564 152 23.8054 152H109.143C110.592 152 111.73 150.861 111.73 149.411V118.337C111.73 116.887 110.592 115.748 109.143 115.748H100.966V105.597C100.966 104.147 99.8276 103.008 98.3786 103.008H74.1591V74.0061C82.9568 71.6238 90.7712 65.0985 96.9813 55.8801ZM127.67 15.5884C126.531 29.1571 116.336 40.9649 101.432 48.3189C106.141 38.9969 109.453 27.8106 110.799 15.5884H127.67ZM5.27858 15.5884H22.1494C23.5467 27.8106 26.807 38.9969 31.5163 48.3189C16.612 40.9131 6.4171 29.1053 5.27858 15.5884ZM106.555 146.821H26.393V120.927H34.5697H98.3786H106.555V146.821ZM95.791 115.8H37.1572V108.238H61.3767H71.5716H95.791V115.8ZM63.9642 103.06V71.9864C63.9642 70.7434 63.0844 69.7077 61.8942 69.4487C42.2805 65.5646 27.3762 38.2201 26.6517 5.23066H106.348C105.624 38.1683 90.7195 65.5646 71.1058 69.4487C69.9156 69.7077 69.0358 70.7434 69.0358 71.9864V103.06H63.9642ZM78.2992 53.1353C78.8167 53.1353 79.386 52.9799 79.8 52.6174C80.4728 52.0995 80.8868 51.3227 80.8868 50.494L80.628 38.8934L87.6661 29.6232C88.1836 28.9499 88.3389 28.0695 88.0801 27.2409C87.8214 26.4123 87.2004 25.7908 86.3724 25.5836L75.2459 22.2174L68.6218 12.6882C67.6385 11.29 65.3615 11.29 64.3782 12.6882L57.7541 22.2174L46.6276 25.5836C45.7996 25.8426 45.1786 26.4641 44.9199 27.2409C44.6611 28.0695 44.8163 28.9499 45.3338 29.6232L52.372 38.8934L52.1132 50.494C52.1132 51.3227 52.4755 52.1513 53.2 52.6174C53.8728 53.1353 54.7525 53.2388 55.5805 52.9799L66.5518 49.1475L77.5229 52.9799C77.7299 53.0835 77.9887 53.1353 78.2992 53.1353ZM75.6082 46.8688L67.328 43.9687C67.0692 43.8651 66.7588 43.8133 66.5 43.8133C66.2412 43.8133 65.9307 43.8651 65.672 43.9687L57.3918 46.8688L57.5988 38.0647C57.5988 37.4951 57.4436 36.9254 57.0813 36.4593L51.751 29.4678L60.1346 26.9302C60.7039 26.7748 61.1697 26.4123 61.5319 25.9462L66.5518 18.7475L71.5716 25.9462C71.8303 26.4123 72.2961 26.7748 72.8653 26.9302L81.249 29.4678L75.9704 36.4593C75.6082 36.9254 75.4529 37.4951 75.4529 38.0647L75.6082 46.8688Z"
      fill="white"
    />
  </svg>
);
