import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="min-h-screen flex-col flex">
        <Navbar />
        <h1 className="grow">Herzlich Willkommen im RGC</h1>
        <Footer />
      </main>
    </>
  );
}
