import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { PostCard } from "../components/PostCard";

type PostAttributes = {
  title: string;
  description: string;
  previewText: string;
  publishedAt: string;
  mainImage: {
    data: {
      attributes: {
        formats: {
          small: {
            url: string;
          };
        };
      };
    };
  };
};

type Post = {
  id: number;
  attributes: PostAttributes;
};

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async () => {
  const res = await fetch(
    `${process.env.CMS_URL}/api/posts?sort=chronologicalPosition:desc&populate=*`,
    {
      headers: { Authorization: `Bearer ${process.env.CMS_TOKEN}` },
    }
  );
  const data: { data: Post[] } = await res.json();
  return {
    props: { posts: data.data },
  };
};

export default function Posts({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-stone-50 h-screen">
        <main className="max-w-[850px] mx-auto">
          <div className="flex flex-col gap-8">
            {posts.map((post, index) => (
              <PostCard
                postID={post.id}
                key={post.id}
                title={post.attributes.title}
                previewText={post.attributes.previewText}
                publishedDate={new Date(post.attributes.publishedAt)}
                previewImage={
                  post.attributes.mainImage.data.attributes.formats.small.url
                }
                imageOrder={index % 2 === 0 ? "first" : "last"}
              />
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
