import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import ReactMarkdown from "react-markdown";
import Link from "next/link";

type PostAttributes = {
  title: string;
  description: string;
};

type Post = {
  id: number;
  attributes: PostAttributes;
};

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async () => {
  const res = await fetch(
    `${process.env.CMS_URL}/api/posts?sort=chronologicalPosition:desc`,
    {
      headers: { Authorization: `Bearer ${process.env.CMS_TOKEN}` },
    }
  );
  const data: { data: Post[] } = await res.json();
  return {
    props: { posts: data.data },
  };
};

export default function Posts({
  posts,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {posts.map((post) => {
            return (
              <li key={post.id}>
                <Link
                  href={`/posts/${post.id.toString()}`}
                  className="prose prose-img:w-96"
                >
                  <ReactMarkdown>{post.attributes.title}</ReactMarkdown>
                </Link>
              </li>
            );
          })}
        </div>
      </main>
    </>
  );
}
