import Head from "next/head";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";

type PostAttributes = {
  title: string;
  description: string;
};

type Post = {
  id: number;
  attributes: PostAttributes;
};

export const getServerSideProps: GetServerSideProps<{
  posts: Post[];
}> = async () => {
  const res = await fetch(`${process.env.CMS_URL}/api/posts`, {
    headers: { Authorization: `Bearer ${process.env.CMS_TOKEN}` },
  });
  const data: { data: Post[] } = await res.json();
  console.log(data);
  return {
    props: {
      posts: data.data,
    },
  };
};

export default function Posts({
  posts,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {posts.map((post) => {
            return (
              <li key={post.attributes.title}>
                <div>{post.attributes.title}</div>
                <div>{post.attributes.description}</div>
              </li>
            );
          })}
        </div>
      </main>
    </>
  );
}
